//
//  UpcomingMoviesModels.swift
//  CineApp
//
//  Created by Giovane Silva de Menezes Cavalcante on 05/01/19.
//  Copyright (c) 2019 GSMenezes. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct UpcomingMoviesScene {
    struct FetchMovies {
        
        struct Request {
            
        }
        
        struct Response {
            let state: State
            
            enum State {
                case success(upcomingMovies: [MovieResult])
                case failure(errorMessage: String)
            }
        }
        
        struct ViewModel {
            let state: State
            
            struct CellModel{
                let title: String
                let releaseDate: String
                let backdropPath: String
                let genre: String
            }
            
            enum State {
                case success(upcomingMovies: [CellModel])
                case failure(errorMessage: String)
            }
        }
    }
    
    struct SelectMovie {
        
        struct Request {
            let index: Int
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
