//
//  SearchMoviesConfigurator.swift
//  CineApp
//
//  Created by Giovane Silva de Menezes Cavalcante on 08/01/19.
//  Copyright (c) 2019 GSMenezes. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension SearchMoviesInteractor: SearchMoviesViewControllerOutput, SearchMoviesRouterDataSource, SearchMoviesRouterDataDestination {
}

extension SearchMoviesPresenter: SearchMoviesInteractorOutput {
}

class SearchMoviesConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = SearchMoviesConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: SearchMoviesViewController) {
        
        let presenter = SearchMoviesPresenter()
        presenter.output = viewController
        
        let interactor = SearchMoviesInteractor()
        interactor.output = presenter
        
        let router = SearchMoviesRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
